### PR TITLE
Perf

### PR DESCRIPTION
**Pull request by merisbahti**
The best version of this that I've found.

Some minor patches by me, such as making it send an empty array of suggestions if chat-gpt didn't come up with a response in time. This lets other LSP's give their suggestions since helix will otherwise not show any suggestions from other lsps

### CODE REVIEW

**Comment by sigmaSd** [comment]
Hello you seem to have based this pr on my fork, maybe that is not on purpose, since it doesn't seem related to the pr

**Comment by merisbahti** [comment]
Totally intentional! Your fork rocks and I couldn't have made it work without it.

**Comment by merisbahti** [comment]
Or do you think that these suggestions would be better for your fork? I dont see much prs being merged here lately.

**Comment by sigmaSd** [comment]
I prefer for stuff to be merged upstream,I think you should rebase your pr ontop of this repo, so you have one commit instead of the current 20 commits

**Comment by leona** [comment]
I haven't had much time to review stuff, apologies. But I'm going to close this as even the README changes mention this is for a fork. If you'd like to open a new one with just fixes/improvements that'd be appreciated though.

**Pull request closed without merging**
